import { 
  Terminal, Zap, Shield, Apple, Code, MessageSquare, Rocket, TrendingUp, Sparkles, Heart, Brain, 
  ShieldCheck, Settings, Globe, Database, Boxes, Atom, Infinity, Layers, Ship, Fingerprint, 
  Gamepad2, Binary, Activity, Anchor, Utensils, Landmark, MessageCircle,
  LineChart, Wallet, Bitcoin, Clock, Users, Lightbulb, Moon, Dumbbell, Bot, CloudLightning
} from 'lucide-react';

export const guidesData = [
  {
    title: "Python 2026: Guía Moderna",
    slug: "python-moderno",
    excerpt: "Domina Python en la era de la IA, con tipos estáticos y agentes autónomos.",
    icon: Terminal,
    color: "green",
    image: "/images/guias/python.png",
    readTime: "18 min",
    tags: ["IA", "Python", "Back-end"],
    category: "tecnologia"
  },
  {
    title: "JavaScript ES2026+: Ecosistema",
    slug: "javascript-es2026",
    excerpt: "Nuevos operadores, Temporal API y el futuro de la web reactiva.",
    icon: Zap,
    color: "amber",
    image: "/images/guias/javascript.png",
    readTime: "15 min",
    tags: ["JavaScript", "Web", "Next.js"],
    category: "tecnologia"
  },
  {
    title: "Seguridad para Desarrolladores",
    slug: "seguridad-desarrolladores",
    excerpt: "Protege tus apps contra inyecciones de prompt y ataques modernos.",
    icon: Shield,
    color: "blue",
    image: "/images/guias/seguridad.png",
    readTime: "20 min",
    tags: ["Seguridad", "DevSecOps", "Cloud"],
    category: "tecnologia"
  },
  {
    title: "Alimentación Saludable: Guía Práctica",
    slug: "alimentacion-saludable",
    excerpt: "Aprende a comer de forma saludable y sostenible. Sin dietas de moda.",
    icon: Apple,
    color: "emerald",
    image: "/images/guias/alimentacion.png",
    readTime: "14 min",
    tags: ["Salud", "Nutrición", "Bienestar"],
    category: "bienestar"
  },
  {
    title: "Aprender a Programar desde Cero",
    slug: "aprender-a-programar",
    excerpt: "Todo lo que necesitas saber para empezar en el mundo del desarrollo.",
    icon: Code,
    color: "violet",
    image: "/images/guias/programar.png",
    readTime: "15 min",
    tags: ["Tecnología", "Programación", "Educación"],
    category: "tecnologia"
  },
  {
    title: "Comunicación Efectiva",
    slug: "comunicacion-efectiva",
    excerpt: "Mejora tus habilidades sociales y aprende a escuchar activamente.",
    icon: MessageSquare,
    color: "indigo",
    image: "/images/guias/comunicacion.png",
    readTime: "13 min",
    tags: ["Habilidades Blandas", "Liderazgo"],
    category: "crecimiento"
  },
  {
    title: "Emprendimiento Digital",
    slug: "emprendimiento-digital",
    excerpt: "Inicia tu negocio online en 2026. Del concepto a la escalabilidad.",
    icon: Rocket,
    color: "orange",
    image: "/images/guias/emprendimiento.png",
    readTime: "16 min",
    tags: ["Negocios", "Marketing Digital"],
    category: "finanzas"
  },
  {
    title: "Cómo Ahorrar Dinero",
    slug: "como-ahorrar-dinero",
    excerpt: "Estrategias probadas para construir hábitos financieros saludables.",
    icon: TrendingUp,
    color: "teal",
    image: "/images/guias/ahorro.png",
    readTime: "12 min",
    tags: ["Finanzas", "Ahorro"],
    category: "finanzas"
  },
  {
    title: "10 Hábitos Productivos",
    slug: "habitos-productivos",
    excerpt: "Rutinas y sistemas de las personas más exitosas del mundo.",
    icon: Sparkles,
    color: "slate",
    image: "/images/guias/habitos.png",
    readTime: "10 min",
    tags: ["Productividad", "Hábitos"],
    category: "crecimiento"
  },
  {
    title: "Guía de Bienestar Mental",
    slug: "bienestar-mental",
    excerpt: "Técnicas basadas en psicología para manejar el estrés diario.",
    icon: Heart,
    color: "rose",
    image: "/images/guias/bienestar.png",
    readTime: "11 min",
    tags: ["Salud Mental", "Mindfulness"],
    category: "bienestar"
  },
  {
    title: "Inteligencia Emocional",
    slug: "inteligencia-emocional",
    excerpt: "Reconoce y gestiona tus emociones y las de los demás.",
    icon: Brain,
    color: "violet",
    image: "/images/guias/inteligencia.png",
    readTime: "13 min",
    tags: ["Crecimiento", "Emociones"],
    category: "crecimiento"
  },
  {
    title: "TypeScript Maestro",
    slug: "typescript-maestro",
    excerpt: "Domina el tipado estático y construye aplicaciones empresariales robustas.",
    icon: ShieldCheck,
    color: "blue",
    image: "/images/guias/typescript.png",
    readTime: "22 min",
    tags: ["TypeScript", "Web", "Clean Code"],
    category: "tecnologia"
  },
  {
    title: "Rust para Sistemas",
    slug: "rust-seguridad",
    excerpt: "El lenguaje que redefine el rendimiento y la seguridad de memoria.",
    icon: Settings,
    color: "orange",
    image: "/images/guias/rust.png",
    readTime: "25 min",
    tags: ["Rust", "Sistemas", "Backend"],
    category: "tecnologia"
  },
  {
    title: "Microservicios con Go",
    slug: "go-microservicios",
    excerpt: "Arquitecturas distribuidas de alto rendimiento con el lenguaje de las nubes.",
    icon: Globe,
    color: "teal",
    image: "/images/guias/go.png",
    readTime: "20 min",
    tags: ["Go", "Cloud", "Microservicios"],
    category: "tecnologia"
  },
  {
    title: "SQL Moderno Avanzado",
    slug: "sql-avanzado",
    excerpt: "De consultas básicas a optimización de PostgreSQL y arquitecturas escalables.",
    icon: Database,
    color: "blue",
    image: "/images/guias/sql.png",
    readTime: "18 min",
    tags: ["SQL", "Datos", "PostgreSQL"],
    category: "tecnologia"
  },
  {
    title: "Bases de Datos NoSQL",
    slug: "arquitectura-nosql",
    excerpt: "Cuándo y cómo utilizar MongoDB, Redis y Cassandra en tus proyectos.",
    icon: Boxes,
    color: "emerald",
    image: "/images/guias/nosql.png",
    readTime: "17 min",
    tags: ["NoSQL", "Performance", "Big Data"],
    category: "tecnologia"
  },
  {
    title: "React 19 & RSC",
    slug: "react-19-rsc",
    excerpt: "Server Components, Actions y el futuro del desarrollo front-end.",
    icon: Atom,
    color: "indigo",
    image: "/images/guias/react.png",
    readTime: "24 min",
    tags: ["React", "Front-end", "Performance"],
    category: "tecnologia"
  },
  {
    title: "DevSecOps & CI/CD",
    slug: "devsecops-pipeline",
    excerpt: "Automatización y seguridad integrada en el ciclo de vida del software.",
    icon: Infinity,
    color: "slate",
    image: "/images/guias/devsecops.png",
    readTime: "21 min",
    tags: ["DevOps", "Seguridad", "Automation"],
    category: "tecnologia"
  },
  {
    title: "IA Generativa para Devs",
    slug: "ia-generativa-llm",
    excerpt: "Integrando Large Language Models y agentes autónomos en tus aplicaciones.",
    icon: Sparkles,
    color: "violet",
    image: "/images/guias/ia.png",
    readTime: "23 min",
    tags: ["IA", "LLM", "Innovación"],
    category: "tecnologia"
  },
  {
    title: "Arquitectura de Software",
    slug: "patrones-diseno",
    excerpt: "Patrones de diseño modernos, principios SOLID y código limpio.",
    icon: Layers,
    color: "blue",
    image: "/images/guias/arquitectura.png",
    readTime: "22 min",
    tags: ["Diseño", "Arquitectura", "SOLID"],
    category: "tecnologia"
  },
  {
    title: "Kubernetes & Docker",
    slug: "kubernetes-escala",
    excerpt: "Orquestación de contenedores y despliegues masivos en la nube.",
    icon: Ship,
    color: "indigo",
    image: "/images/guias/kubernetes.png",
    readTime: "26 min",
    tags: ["Cloud", "K8s", "Docker"],
    category: "tecnologia"
  },
  {
    title: "Flutter Multiplataforma",
    slug: "flutter-pro",
    excerpt: "Crea aplicaciones nativas de alto rendimiento desde un solo código.",
    icon: Rocket,
    color: "blue",
    image: "/images/guias/flutter.png",
    readTime: "19 min",
    tags: ["Móvil", "Flutter", "Dart"],
    category: "tecnologia"
  },
  {
    title: "Ethical Hacking",
    slug: "hacking-etico",
    excerpt: "Fundamentos de pentesting y defensa activa en redes modernas.",
    icon: Fingerprint,
    color: "slate",
    image: "/images/guias/hacking.png",
    readTime: "25 min",
    tags: ["Ciberseguridad", "Hacking", "Linux"],
    category: "tecnologia"
  },
  {
    title: "Gamedev con Unity/Godot",
    slug: "gamedev-unity-godot",
    excerpt: "El arte de crear videojuegos: del motor gráfico al lanzamiento comercial.",
    icon: Gamepad2,
    color: "violet",
    image: "/images/guias/gamedev.png",
    readTime: "28 min",
    tags: ["Juegos", "C#", "Godot"],
    category: "tecnologia"
  },
  {
    title: "Machine Learning 101",
    slug: "machine-learning-python",
    excerpt: "Entrena modelos de predicción y clasificación con Scikit-Learn y PyTorch.",
    icon: Binary,
    color: "orange",
    image: "/images/guias/ml.png",
    readTime: "24 min",
    tags: ["Python", "CIencia de Datos", "ML"],
    category: "tecnologia"
  },
  {
    title: "Biohacking & Longevidad",
    slug: "biohacking-longevidad",
    excerpt: "Estrategias biológicas para optimizar tu salud y extender tu vida útil.",
    icon: Activity,
    color: "emerald",
    image: "/images/guias/biohacking.png",
    readTime: "20 min",
    tags: ["Salud", "Biohacking", "Longevidad"],
    category: "bienestar"
  },
  {
    title: "Estoicismo Práctico",
    slug: "estoicismo-practico",
    excerpt: "Resiliencia emocional y enfoque profundo en la era de la distracción.",
    icon: Anchor,
    color: "slate",
    image: "/images/guias/estoicismo.png",
    readTime: "16 min",
    tags: ["Filosofía", "Enfoque", "Paz"],
    category: "crecimiento"
  },
  {
    title: "Cocina y Nutrición Batch",
    slug: "cocina-nutricion-batch",
    excerpt: "Aprende a cocinar para toda la semana en solo 3 horas sin sacrificar salud.",
    icon: Utensils,
    color: "orange",
    image: "/images/guias/cocina.png",
    readTime: "15 min",
    tags: ["Cocina", "Salud", "Eficiencia"],
    category: "bienestar"
  },
  {
    title: "Inversión Inmobiliaria",
    slug: "inversion-inmobiliaria",
    excerpt: "Estrategias para construir patrimonio real a través del mercado de bienes raíces.",
    icon: Landmark,
    color: "emerald",
    image: "/images/guias/inmobiliaria.png",
    readTime: "19 min",
    tags: ["Finanzas", "Patrimonio", "Inversión"],
    category: "finanzas"
  },
  {
    title: "Narrativa & Storytelling",
    slug: "narrativa-storytelling",
    excerpt: "El arte de cautivar audiencias y comunicar ideas con impacto masivo.",
    icon: MessageCircle,
    color: "rose",
    image: "/images/guias/storytelling.png",
    readTime: "17 min",
    tags: ["Comunicación", "Liderazgo", "Storytelling"],
    category: "crecimiento"
  },
  {
    title: "Inversión Mínima: ETFs y Fondos",
    slug: "inversion-etfs-bolsa",
    excerpt: "Construye tu retiro y patrimonio usando estrategias pasivas y de bajo riesgo en la bolsa.",
    icon: LineChart,
    color: "emerald",
    image: "/images/guias/etfs.png",
    readTime: "22 min",
    tags: ["Dinero", "Bolsa", "Inversión"],
    category: "finanzas"
  },
  {
    title: "Psicología del Dinero",
    slug: "psicologia-dinero",
    excerpt: "Por qué tomamos malas decisiones financieras y cómo sanar tu relación con el consumo.",
    icon: Wallet,
    color: "amber",
    image: "/images/guias/psicologia_dinero.png",
    readTime: "18 min",
    tags: ["Ahorro", "Mentalidad", "Finanzas"],
    category: "finanzas"
  },
  {
    title: "Cripto y Web3 Seguro",
    slug: "cripto-web3-seguro",
    excerpt: "Adéntrate en Blockchain, contratos inteligentes y billeteras desconectadas (cold wallets) sin caer en estafas.",
    icon: Bitcoin,
    color: "orange",
    image: "/images/guias/cripto.png",
    readTime: "24 min",
    tags: ["Blockchain", "Criptomonedas", "Web3"],
    category: "finanzas"
  },
  {
    title: "Gestión de Tiempo y Deep Work",
    slug: "gestion-tiempo-avanzada",
    excerpt: "Arquitectura del trabajo profundo. Destruye la procrastinación utilizando el enfoque Time-Blocking iterativo.",
    icon: Clock,
    color: "violet",
    image: "/images/guias/tiempo.png",
    readTime: "15 min",
    tags: ["Productividad", "Eficiencia", "Enfoque"],
    category: "crecimiento"
  },
  {
    title: "Liderazgo en Entornos Remotos",
    slug: "liderazgo-remoto",
    excerpt: "Cómo mantener equipos motivados y eficientes en ecosistemas 100% distribuidos por el mundo.",
    icon: Users,
    color: "indigo",
    image: "/images/guias/liderazgo.png",
    readTime: "16 min",
    tags: ["Profesional", "Equipos", "Empresas"],
    category: "crecimiento"
  },
  {
    title: "Metacognición: Aprender a Aprender",
    slug: "aprender-a-aprender",
    excerpt: "Mapas mentales, repetición espaciada y el método Feynman para interiorizar cualquier tema al doble de velocidad.",
    icon: Lightbulb,
    color: "rose",
    image: "/images/guias/aprender.png",
    readTime: "20 min",
    tags: ["Educación", "Procesos", "Crecimiento"],
    category: "crecimiento"
  },
  {
    title: "La Arquitectura del Sueño",
    slug: "optimizacion-sueno",
    excerpt: "Biohacking nocturno para reparar tejidos profundos. Higiene circadiana en la era de los dispositivos.",
    icon: Moon,
    color: "slate",
    image: "/images/guias/sueno.png",
    readTime: "19 min",
    tags: ["Salud", "Descanso", "Longevidad"],
    category: "bienestar"
  },
  {
    title: "Entrenamiento de Fuerza Metabólico",
    slug: "entrenamiento-fuerza",
    excerpt: "La hipertrofia no es vanidad, es salud. Un enfoque científico para transformar tus articulaciones y metabolismo.",
    icon: Dumbbell,
    color: "teal",
    image: "/images/guias/fuerza.png",
    readTime: "26 min",
    tags: ["Deporte", "Biomecánica", "Fitness"],
    category: "bienestar"
  },
  {
    title: "Ingeniería de Prompts Estructurados",
    slug: "ingenieria-prompts",
    excerpt: "Comunícate con Lógicas de Lenguaje Mayor a través de restricciones y esquemas algorítmicos complejos.",
    icon: Bot,
    color: "blue",
    image: "/images/guias/prompts.png",
    readTime: "21 min",
    tags: ["IA", "Automatización", "Productividad"],
    category: "tecnologia"
  },
  {
    title: "Bases del Entorno Serverless Edge",
    slug: "desarrollo-serverless",
    excerpt: "Entiende Cloudflare Workers, bases de datos Edge y por qué el backend estático está siendo reemplazado rápidamente.",
    icon: CloudLightning,
    color: "blue",
    image: "/images/guias/serverless.png",
    readTime: "25 min",
    tags: ["DevOps", "Backend", "Escalabilidad"],
    category: "tecnologia"
  },
  {
    title: "Ciberseguridad Personal",
    slug: "ciberseguridad-personal",
    excerpt: "Protege tus contraseñas, datos bancarios y privacidad contra las amenazas digitales más comunes de 2026. Sin jerga técnica.",
    icon: Shield,
    color: "red",
    image: "/images/guias/seguridad.png",
    readTime: "20 min",
    tags: ["Seguridad", "Privacidad", "Digital"],
    category: "tecnologia"
  },
  {
    title: "Primeros Auxilios Emocionales",
    slug: "primeros-auxilios-emocionales",
    excerpt: "Protocolos basados en evidencia para manejar ataques de pánico, ansiedad, ira y sobrecarga emocional en el momento.",
    icon: Heart,
    color: "pink",
    image: "/images/guias/bienestar.png",
    readTime: "22 min",
    tags: ["Salud Mental", "Bienestar", "Psicología"],
    category: "bienestar"
  },
  {
    title: "Freelancing Profesional",
    slug: "freelancing-profesional",
    excerpt: "De cero a profesional independiente con ingresos estables. Precios, clientes, propuestas, finanzas y escalamiento.",
    icon: Rocket,
    color: "emerald",
    image: "/images/guias/emprendimiento.png",
    readTime: "24 min",
    tags: ["Carrera", "Finanzas", "Negocio"],
    category: "finanzas"
  },
  {
    title: "Lectura Veloz y Retención",
    slug: "lectura-veloz-retencion",
    excerpt: "Triplica tu velocidad de lectura sin perder comprensión. Técnicas científicas, SQ3R y plan de entrenamiento de 30 días.",
    icon: Lightbulb,
    color: "amber",
    image: "/images/guias/aprender.png",
    readTime: "20 min",
    tags: ["Aprendizaje", "Productividad", "Cerebro"],
    category: "crecimiento"
  }
];
